---
# Helm repos
rancher_helm_repo_name: rancher-latest
rancher_helm_repo_url: "https://releases.rancher.com/server-charts/latest"

cert_manager_helm_repo_name: jetstack
cert_manager_helm_repo_url: "https://charts.jetstack.io"

# Namespaces
rancher_namespace: cattle-system
cert_manager_namespace: cert-manager

# Optional pinning (leave empty to get latest)
rancher_chart_version: ""
cert_manager_chart_version: ""

# Rancher config
rancher_hostname: "{{ vault_hostname }}"
rancher_replicas: 1
rancher_bootstrap_password: "{{ vault_rancher_bootstrap_password | default('admin') }}"
